# Generated by Django 4.1.6 on 2023-02-13 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_remove_video_categoria_categoria_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="video",
        ),
        migrations.AddField(
            model_name="video",
            name="categoria",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="videos.categoria",
            ),
        ),
    ]
