# Generated by Django 4.1.6 on 2023-02-11 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0008_alter_video_categoriaid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="categoriaId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="videos.categoria"
            ),
        ),
    ]
