# Generated by Django 4.1.6 on 2023-02-11 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0010_alter_video_categoriaid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="categoriaId",
        ),
        migrations.AddField(
            model_name="video",
            name="categoria",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="videos.categoria",
            ),
        ),
    ]
