# Generated by Django 4.1.6 on 2023-02-11 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0011_remove_video_categoriaid_video_categoria"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="categoria",
        ),
    ]
